# Generated by Django 2.1.7 on 2019-03-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_auto_20190319_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='email_confirm',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
